version: '3'
services:
  jenkins:
    container_name: lab-jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/config:/var/jenkins_home
    networks:
      - net
networks:
  net:
